Try adding an error if activation and loss are mismatched
Example output:

```
>>> classifier.compile(loss="sparse_categorical_crossentropy")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mattdangerw/checkout/keras-nlp/keras_nlp/models/task.py", line 82, in compile
    self._check_from_logits_mismatch()
  File "/home/mattdangerw/checkout/keras-nlp/keras_nlp/models/task.py", line 72, in _check_from_logits_mismatch
    raise ValueError(
ValueError: The `loss` passed to `compile()` expects softmax probability output, but the model is configured to output logits (`activation=None`). This will not converge! Pass `from_logits=True` to your loss, e.g. `loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True)`.
```