Switch slice op
This does not appear to work with XLA. Error message:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 to
node `while/transformer_layer_0/cached_multi_head_attention/TensorStridedSliceUpdate`
with op TensorStridedSliceUpdate must be a compile-time constant.

XLA compilation requires that operator arguments that represent shapes
or dimensions be evaluated to concrete values at compile time. This
error means that a shape or dimension argument could not be evaluated at
compile time, usually because the value of the argument depends on a
parameter to the computation, on a variable, or on a stateful operation
such as a random number generator.
```